version=0.1.0

org.gradle.jvmargs=-Xmx1500m -Dfile.encoding=UTF-8
# Default memory args are -Xmx512m "-XX:MaxMetaspaceSize=384m".
# Pipeline starts with -Xmx1024m as default value.
#
# SDMX
#
sdmx_version=2.0.6
sdmx30_infomodel_version=2.0.0
sdmx30_internal_version=2.0.0
sdmx_core_version=2.4.0
#
# Dependencies
#
# Alphabetical order (IDEA -> Edit -> Sort lines)
#
allpairs4j_version=1.0.1
assertj_core_version=3.27.7
aws_sdk_core_version=1.12.780
azure_identity_version=1.15.0
caffeine_version=3.1.8
commons_beanutils_version=1.11.0
commons_collections4_version=4.5.0
commons_compress_version=1.27.1
commons_io_version=2.21.0
commons_lang3_version=3.19.0
fastutil_core_version=8.5.18
feign_version=13.6
gcp_iamcredentials_version=2.56.0
grpc_bom_version=1.75.0
jackson_bom_version=3.1.1
jackson_version=2.18.6
jettison_version=1.5.4
json_path_version=2.9.0
json_smart_version=2.5.2
json_unit_version=3.2.2
json_version=20240303
junit_jupiter_version=5.10.2
kryo_version=5.6.2
log4j2_version=2.25.4
lombok_version=1.18.42
netty_version=4.2.13.Final
okhttp_version=4.12.0
opencsv_version=5.12.0
opentelemetry_instrumentation_version=2.26.1
plexus_utils_version=3.6.1
resilience4j_version=2.3.0
rest_assured_version=5.4.0
slf4j_version=2.0.17
spring_boot_version=4.0.6
spring_dependency_management_version=1.1.7
springdoc_openapi_version=3.0.1
threetenbp_version=1.6.8
tomcat_version=11.0.21
woodstox_core_version=7.1.1
xmlbeans_version=3.0.0
