version=0.1.0

org.gradle.jvmargs=-Xmx1500m -Dfile.encoding=UTF-8
# Default memory args are -Xmx512m "-XX:MaxMetaspaceSize=384m".
# Pipeline starts with -Xmx1024m as default value.
#
# SDMX
#
sdmx_version=2.0.6
sdmx30_infomodel_version=2.0.0
sdmx30_internal_version=2.0.0
#
# Dependencies
#
# Alphabetical order (IDEA -> Edit -> Sort lines)
#
feign_version=13.6
okhttp_version=4.12.0
resilience4j_version=2.3.0
org_apache_commons_commons_collections4_version=4.5.0
org_apache_commons_commons_lang3_version=3.19.0
slf4j_version=2.0.17
# Caching
caffeine_version=3.1.8
# Cloud provider Redis authentication
azure_identity_version=1.15.0
aws_sdk_core_version=1.12.780
gcp_iamcredentials_version=2.56.0
