name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    uses: epam/ai-dial-ci/.github/workflows/java_test.yml@3.2.0
    secrets: inherit
    permissions:
      contents: read
      actions: write
      checks: write
      security-events: write
    with:
      bypass-checks: false
      style-checks-enabled: true
      style-checks-bypassed: false
      code-checks-enabled: true
      code-checks-bypassed: false
      ort-enabled: true
      ort-bypassed: false
      ort-version: "latest"
      java-version: "25"
      java-distribution: "corretto"
      runs-on: '["ubuntu-24.04"]'

  dependency-graph:
    # Do not submit dependencies on private repos - GitHub Advanced Security is not enabled
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
      - uses: epam/ai-dial-ci/actions/java_prepare@3.2.0
        with:
          java-version: "25"
          java-distribution: "corretto"
      - uses: gradle/actions/dependency-submission@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
        with:
          dependency-graph: generate-and-upload
          artifact-retention-days: 1
        env:
          # PAT is used temporarily
          GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
          GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}

  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
      - uses: epam/ai-dial-ci/actions/java_prepare@3.2.0
        with:
          java-version: "25"
          java-distribution: "corretto"
          build-scan-publish: true
      - run: ./gradlew build -x test
        env:
          # PAT is used temporarily
          GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
          GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}

  docker_build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
      packages: read
    strategy:
      matrix:
        include:
          - image-name: "epam/statgpt-sdmx-proxy"
            dockerfile: "docker/sdmx-proxy.Dockerfile"
          - image-name: "epam/statgpt-sdmx-proxy-config-server"
            dockerfile: "docker/config-server.Dockerfile"

    steps:
      - name: Maximize build space
        uses: nepalevov/maximize-build-space@046c48361370e2f3fa758bd2f10c6ce29109ef62 # v1.1.0
        if: false # Maximize build space by removing unwanted software if set to true
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-large-packages: "true"
          remove-cached-tools: "true"
          remove-swapfile: "true"
          remove-java: "true"
          remove-swift: "true"
          remove-julia: "true"
          remove-browsers: "true"
          remove-cloud-tools: "true"
          remove-kubernetes-tools: "true"
          remove-powershell: "true"
          remove-container-tools: "true"
          remove-rust: "true"
          remove-python: "true"
          remove-node: "true"
          remove-go: "true"
          remove-ruby: "true"
          docker-cleanup: "true"
          set-tmpdir: "true"

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true

      - uses: ./.github/actions/build_docker
        with:
          image-name: ghcr.io/${{ matrix.image-name }}
          dockerfile-path: ${{ matrix.dockerfile }}
          image-tag: test
          push-enabled: false
          trivy-enabled: true
          bypass-checks: false
          trivy-severity: "CRITICAL,HIGH"
          trivy-severity-for-sarif: "CRITICAL,HIGH"
          trivy-limit-severities-for-sarif: true
          gpr-username: ${{ github.actor }}
          gpr-password: ${{ secrets.GITHUB_TOKEN }}
          platforms: "linux/amd64"
