name: Release Workflow

on:
  push:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    permissions:
      contents: read
      actions: write
      checks: write
      security-events: write
    with:
      bypass-checks: false
      style-checks-enabled: true
      style-checks-bypassed: false
      code-checks-enabled: true
      code-checks-bypassed: false
      ort-enabled: true
      ort-bypassed: false
      ort-version: "85.0.0" # HACK: pin ORT version due to java.util.NoSuchElementException in 85.1.0
      ort-config-repository: "https://github.com/oss-review-toolkit/ort-config.git"
      ort-config-revision: "5650fed55a20397b9abb9017a0c6bb674dc8481d"
      java-version: "25"
      java-distribution: "corretto"
      runs-on: '["ubuntu-24.04"]'

  dependency-graph:
    # Do not submit dependencies on private repos - GitHub Advanced Security is not enabled
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write # to submit dependency graph
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true
      - uses: epam/ai-dial-ci/actions/java_prepare@4.8.0
        with:
          java-version: "25"
          java-distribution: "corretto"
      - uses: gradle/actions/dependency-submission@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          dependency-graph: generate-and-submit # Default value is 'generate-submit-and-upload', but we don't need job artifacts here
        env:
          # PAT is used temporarily
          GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
          GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}

  calculate_version:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      next-version: ${{ steps.semantic_versioning.outputs.next-version }}
      is-latest: ${{ steps.semantic_versioning.outputs.is-latest }}
      latest-stable-tag: ${{ steps.semantic_versioning.outputs.latest-stable-tag }}
      changelog-mode: ${{ steps.semantic_versioning.outputs.changelog-mode }}
    steps:
      - uses: epam/ai-dial-ci/actions/semantic_versioning@4.8.0
        id: semantic_versioning
        with:
          promote: true

  release:
    runs-on: ubuntu-24.04
    needs: [test, calculate_version]
    permissions:
      contents: read
      packages: write
      security-events: write
    strategy:
      matrix:
        include:
          - image-name: "epam/statgpt-sdmx-proxy"
            dockerfile: "docker/sdmx-proxy.Dockerfile"
          - image-name: "epam/statgpt-sdmx-proxy-config-server"
            dockerfile: "docker/config-server.Dockerfile"

    steps:
      - name: Maximize build space
        uses: nepalevov/maximize-build-space@046c48361370e2f3fa758bd2f10c6ce29109ef62 # v1.1.0
        if: false # Maximize build space by removing unwanted software if set to true
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-large-packages: "true"
          remove-cached-tools: "true"
          remove-swapfile: "true"
          remove-java: "true"
          remove-swift: "true"
          remove-julia: "true"
          remove-browsers: "true"
          remove-cloud-tools: "true"
          remove-kubernetes-tools: "true"
          remove-powershell: "true"
          remove-container-tools: "true"
          remove-rust: "true"
          remove-python: "true"
          remove-node: "true"
          remove-go: "true"
          remove-ruby: "true"
          docker-cleanup: "true"
          set-tmpdir: "true"

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}

      - uses: epam/ai-dial-ci/actions/java_prepare@4.8.0
        with:
          java-version: "25"
          java-distribution: "corretto"

      - name: Set version in build.gradle for Docker build
        shell: bash
        run: |
          sed -i -E "s/^([ \t]*version[ \t]*=[ \t]*)[\"'].*[\"']/\1\"${{ needs.calculate_version.outputs.next-version }}\"/g" build.gradle

      - uses: epam/ai-dial-ci/actions/build_docker@4.8.0
        with:
          ghcr-username: ${{ github.actor }}
          ghcr-password: ${{ secrets.ACTIONS_BOT_TOKEN }}
          dockerhub-username: ${{ secrets.DOCKERHUB_LOGIN }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          image-names: |
            ${{ matrix.image-name }}
            ghcr.io/${{ matrix.image-name }}
          image-tags: |
            type=raw,value=${{ startsWith(github.ref, 'refs/heads/release-') && needs.calculate_version.outputs.next-version || 'development' }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/release-') && needs.calculate_version.outputs.is-latest == 'true' }}
          dockerfile-path: ${{ matrix.dockerfile }}
          push-enabled: true
          trivy-enabled: true
          bypass-checks: false
          trivy-severity: "CRITICAL,HIGH"
          trivy-severity-for-sarif: "CRITICAL,HIGH"
          trivy-limit-severities-for-sarif: true
          # PAT is used temporarily
          gpr-username: ${{ secrets.GPR_USERNAME }}
          gpr-password: ${{ secrets.GPR_PASSWORD }}
          platforms: "linux/amd64"

  create_release:
    runs-on: ubuntu-24.04
    needs: [calculate_version, release]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}

      - name: Set version in build.gradle for release
        shell: bash
        run: |
          sed -i -E "s/^([ \t]*version[ \t]*=[ \t]*)[\"'].*[\"']/\1\"${{ needs.calculate_version.outputs.next-version }}\"/g" build.gradle

      - uses: epam/ai-dial-ci/actions/generate_release_notes@4.8.0
        with:
          latest-tag: ${{ needs.calculate_version.outputs.latest-stable-tag }}
          use-merge-base: ${{ needs.calculate_version.outputs.changelog-mode == 'merge-base' }}

      - uses: epam/ai-dial-ci/actions/publish_tag_release@4.8.0
        if: ${{ startsWith(github.ref, 'refs/heads/release-') }}
        with:
          git-user-name: ${{ vars.ACTIONS_BOT_NAME || 'statgpt-actions' }}
          git-user-email: ${{ vars.ACTIONS_BOT_EMAIL || '231008922+statgpt-actions@users.noreply.github.com' }}
          tag-version: ${{ needs.calculate_version.outputs.next-version }}
          changelog-file: "/tmp/my_changelog" # Comes from generate_release_notes step
          draft-stable-releases: true
          extra-commit-command: |
            git add build.gradle
            git commit -m '[skip ci] Update version' || true # Upstream branch may already be updated
